### ISSUE TITLE
Please add a package for blkdiscard to support periodic trim on SSD devices

### ISSUE THREAD

**Issue by salekseev** [CZ-NIC/turris-os#13]
This has already been added to OpenWrt at https://dev.openwrt.org/changeset/48707

Thanks.

**Comment by sairon** [comment]
@miska is there a reason why this patch is in upstream but not in our repo? If not, can you apply it in turris-os?

**Comment by miska** [comment]
No idea why it didn't ended up in our repo, merged now in c3a79ded1e5a2198361ce9ae3c0202085b9d4683

**Comment by sairon** [comment]
Perfect, closing the issue.
