### ISSUE TITLE
XFS filesystems ignored in LuCI Admin

### ISSUE THREAD

**Issue by tomkv** [CZ-NIC/turris-os#15]
The control panel in System | Mount Points ignores XFS formatted volumes and doesn’t allow to choose them for mounting.

Steps to reproduce:

1. have an XFS-formatted volume available (tested with mSATA attached SSD, partitioned using GPT scheme and the first partition formatted using mkfs.xfs, recognized by blkid),
2. Go to System | Mount Points, scroll to Mount Points section, press the Add button,
3. the UUID, Label and Device combo boxes won’t list the volume.

After reformatting the volume to ext4, everything works as it should.

**Comment by m-reiter** [comment]
I have also observed that XFS volumes defined in /etc/config/fstab are not auto mounted at system start. Thought I'd mention it here as it might be related.

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/108
