### ISSUE TITLE
The rrdtool1 graphs for interfaces do not show interface names

### ISSUE THREAD

**Issue by tomkv** [CZ-NIC/turris-os#16]
The LuCI Statistics | Graphs | Interfaces graphs does not show interface names

![luci-statistics-interfaces-without-labels](https://cloud.githubusercontent.com/assets/23433734/20246042/b2966bb0-a9ae-11e6-88c3-510a0a38e251.png)

The configuration for generating the above output is following:

```
<Plugin interface>
	IgnoreSelected false
	Interface eth1
	Interface "6in4-wan6"
	Interface ipsec0
</Plugin>

```
From the output, the user cannot distinguish, which graph is for which interface.

**Comment by wwwdata** [comment]
Did you find a fix for that @tomkv ?

**Comment by tomkv** [comment]
No, I'm just guessing which interface is which, based on the traffic. The graph generators are ELF binaries, not scripts.

**Comment by JamesT42** [comment]
Is ist maybe related to my issue that the collectd version is 4, while OpenWRT Chaos Calmer normally has version 5 of collectd?

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/107
