### ISSUE TITLE
HiDPI support for collectd-rrdtool1 graphs

### ISSUE THREAD

**Issue by tomkv** [CZ-NIC/turris-os#19]
Please support generating of additional set of graphs for HiDPI from rrdtool1. The additional pixels available in HiDPI would greatly help the readability of the graphs.

The existing low-res graphs look like this on HiDPI displays:

![luci-statistics-interfaces-without-labels](https://cloud.githubusercontent.com/assets/23433734/20246085/92821940-a9af-11e6-9581-70d0dc38b165.png)

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/104
