### ISSUE TITLE
Deactivating data collection breaks syslog-ng

### ISSUE THREAD

**Issue by JamesT42** [CZ-NIC/turris-os#28]
Hi!
I'm not sure wheter this is turris OS, updater or foris, but deactivating the data collection breaks syslog-ng

Please see my forum post:
https://forum.turris.cz/t/deactivating-data-collection-breaks-syslog-ng/1280

**Comment by Cynerd** [comment]
This should be fixed in next release. For now you can just create `/etc/syslog-ng.d` directory to fix it.
