### ISSUE TITLE
Update & release tc in order to fully support cake

### ISSUE THREAD

**Issue by dim-geo** [CZ-NIC/turris-os#33]
Latest stable released turris includes cake module without tc patches.

`lsmod | grep cake
sch_cake               18985  0`

`tc qdisc add dev pppoe-wan root cake bandwidth 716kbit besteffort triple-isolate
Unknown qdisc "cake", hence option "bandwidth" is unparsable`

**Comment by Anulap** [comment]
opkg update 
opkg --force-reinstall tc 
and reboot. You are welcome.

**Comment by ValdikSS** [comment]
Why the hell tc got updated without version bump!?

**Comment by sairon** [comment]
@ValdikSS Sorry for that, fixed in 32123c1477cf915726b55aaa18f807fa53a285c8
