### ISSUE TITLE
Please support all tc actions

### ISSUE THREAD

**Issue by dim-geo** [CZ-NIC/turris-os#34]
This is the default kernel configuration of Turris Omnia.
It cannot support pedit action or BPF.
Please make everything a module so we can use all actions.

`CONFIG_NET_ACT_POLICE=m`
`# CONFIG_NET_ACT_GACT is not set`
`CONFIG_NET_ACT_MIRRED=m`
`CONFIG_NET_ACT_IPT=m`
`# CONFIG_NET_ACT_NAT is not set`
`# CONFIG_NET_ACT_PEDIT is not set`
`# CONFIG_NET_ACT_SIMP is not set`
`CONFIG_NET_ACT_SKBEDIT=m`
`# CONFIG_NET_ACT_CSUM is not set`
`# CONFIG_NET_ACT_VLAN is not set`
`# CONFIG_NET_ACT_BPF is not set`
`CONFIG_NET_ACT_CONNMARK=m`

**Comment by miska** [comment]
Enabled in nightly, unless it breaks something will be part of next big release.
