### ISSUE TITLE
Remove `902-debloat_proc.patch`

### ISSUE THREAD

**Issue by SuperQ** [CZ-NIC/turris-os#36]
There is an upstream openwrt kernel patch `902-debloat_proc.patch` that removes a number of useful metrics files from proc.

It would be nice to be able to get metrics from `/proc/net/sockstat` and `/proc/net/netstat` for example.

Either remove the patch, or re-enable the proc values by setting `CONFIG_PROC_STRIPPED=n` in the kernel config.

These proc entries have minimal overhead for hardware as powerful as the turris routers.

**Comment by miska** [comment]
Fixed in nightly, will be part of next release.

**Comment by SuperQ** [comment]
Thanks!
