### ISSUE TITLE
it is unclear that second wifi us 2.4 only

### ISSUE THREAD

**Issue by gorn** [CZ-NIC/turris-os#37]
It is quite confusing for nonexpert how to set up 5g and 2.4g wifi. The reason beeing that when you enable second wifi, it is not mentioned that this is "2.4G". It shoud **at least** be good to add radio button to the wifi2 section which will have only one selection 2.4G (maybe greyed one) and in quiestionmark connected to this "otion" give an explanation. 

In particular explain that "if you want 5G and 2.4G simultaneously, please use wifi1 for 5G and wigi2 for 2.4G"

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/86
