### ISSUE TITLE
Compilation access denied git@git.nic.cz

### ISSUE THREAD

**Issue by loconox** [CZ-NIC/turris-os#4]
Hi,

I'm trying to compile the OS just for the fun and also because maybe one day I'll have my own routeur ;)
I'm using the compile_turris_fix script but I'm having an access denied on the repo git@git.nic.cz:turris/misc-internal. Is there a way to have access to this repo ? Am I doing right ?

Thanks.

**Comment by sairon** [comment]
Hello. That repository is not accessible intentionally. But if I'm not mistaken, it is used only in the `compile_turris_fix` script, which is used by our build machine, so you can ignore it. You might want to take a look at `compile_turris_fw` instead.

There's also a Vagrantfile for bootstrapping of the compilation environment, see https://github.com/CZ-NIC/turris-os/tree/test/vagrant

Alternatively, one of our users made a Dockerfile for the Turris buildroot, you can find it in his repo: https://github.com/samm-git/turris-buildroot
