### ISSUE TITLE
DNS Over DNSSEC does sometimes not find StackOverflow

### ISSUE THREAD

**Issue by the-s-a-m** [CZ-NIC/turris-os#42]
![settingsdnssec](https://cloud.githubusercontent.com/assets/6050624/22099366/601446a8-de2b-11e6-9a54-e9cb425ca3d5.png)

**Comment by vcunat** [comment]
Oh, this issue got missed.  I believe it is OK now; reopen otherwise, please.

There have been multiple similar fixes in knot-resolver since January.  I'm myself using it all the time and I do go to stackoverflow every week at least.
