### ISSUE TITLE
950-add-cake-to-tc.patch out of sync

### ISSUE THREAD

**Issue by fuller42** [CZ-NIC/turris-os#43]
cake was updated ...
https://github.com/CZ-NIC/turris-os/commit/bbbe470ad0de7875bb47ce002f7c62fbdf23ea80
iproute was not.

e.g.
https://github.com/lede-project/source/blob/master/package/network/utils/iproute2/patches/950-add-cake-to-tc.patch

**Comment by miska** [comment]
Both updated to the latest version in test
