### ISSUE TITLE
1-wire not working - error -2

### ISSUE THREAD

**Issue by Weafyr** [CZ-NIC/turris-os#44]
Hello,

When I try `insmod w1-gpio-custom bus0=0,56,0`
Then I get in kernel log:
`
[ 1634.605726] Custom GPIO-based W1 driver version 0.1.1`
`
[ 1634.605858] w1-gpio w1-gpio.0: Failed to parse gpio property for data pin (-2)`
`
[ 1634.613713] w1-gpio: probe of w1-gpio.0 failed with error -2`

You can find patch on this page https://dev.openwrt.org/ticket/219652

Reference to thread's:
https://forum.turris.cz/t/1-wire-ds18b20-teplomer-w1-gpio-error-2/3062
https://www.turris.cz/forum/topic_show.pl?tid=45

**Comment by tmshlvck** [comment]
Fixed in 9bb9c0d15422961f8c955294645924eb7f5e2eb0. Scheduled for inclusion of next TurrisOS release.
