### ISSUE TITLE
setting wifi txpower not functional

### ISSUE THREAD

**Issue by fuller42** [CZ-NIC/turris-os#47]
on v3.5 if wifi region is set to CZ or DE
`iwinfo phy1 txpower`
shows 16dbm regardless of setting in luci `/etc/config/wireless` or setting manually per
`iw phy1 set txpower fixed 18`

works if region is set to `00 `or `US`  ...

signal indeed shows about 5db increased reception at clients

Edit:
also the list of txpower only goes to 19dbm/79mw not the allowed 20dbm/100mw

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/218
