### ISSUE TITLE
Enable config_PADATA (Wireguard performance)

### ISSUE THREAD

**Issue by fmfranz** [CZ-NIC/turris-os#53]
Please enable config_PADATA  to optimize Wireguard performance

**Comment by danrl** [comment]
Yes, that would really help a lot and significantly boost VPN performance when using WireGuard.

**Comment by anarcat** [comment]
according to the wireguard author (@zx2c4), this is not necessary anymore and this ticket should be closed.

**Comment by zx2c4** [comment]
However, you *must* update wireguard to the latest snapshot.

**Comment by anarcat** [comment]
... which was done in #64 - thanks!
