### ISSUE TITLE
HOWTO Openvswitch 2.7.2

### ISSUE THREAD

**Issue by jmguzmanc** [CZ-NIC/turris-os#68]
Hi

I have been trying to make openvswitch work
As mentioned in [Issue 67](https://github.com/CZ-NIC/turris-os/issues/67), openvswitch 2.5 compiles well but does not work, presumably because 2.5 do not support kernel 4.4.

So, I trying to make openvswitch 2.7.2 to work in stable-3.8.5
openvswitch 2.7.2 was included in https://github.com/openwrt/packages 1ef945315b04aa6aeda73fa850482880b8b1520b but it fails to compile because python-six
I tried different versions of python-six (1.10.0, 1.11.0) but they also failed to me.

I imagine that my problem is that I am trying to force those newer packages to work with stable-3.8.5, but I haven´t find other turris-os versions pointing to newer packages.

Is there any other turris-os version I should try, where somebody has succeeded building with newer packages? Maybe one of the devel ones?

Thanks a lot! (and congrats for the great work your are doing)

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/134
