### ISSUE TITLE
Foris storage plugin fails to move data after reboot

### ISSUE THREAD

**Issue by renne** [CZ-NIC/turris-os#83]
The Foris storage plugin formats the selected disks correctly but does not move data from the internal flash to the disk automatically after reboot. I tried all four disks.

![](https://forum.turris.cz/uploads/default/original/2X/4/46213030e84e67ec92e60cbc00a50b734d500119.png)
![](https://forum.turris.cz/uploads/default/original/2X/f/f4f28c70d06f5d3412521b76a216fc67dc6c4fba.png)

**Comment by BKPepe** [comment]
Hello,

This issue is fixed in Turris OS 3.10.3.

Best regards,
