### ISSUE TITLE
Unbound resolver memory leak

### ISSUE THREAD

**Issue by surakin** [CZ-NIC/turris-os#87]
There is a memory leak when using the unbound resolver with an upstream DNS server over TLS.

Looks like it's been fixed a few days ago, see 
https://github.com/openwrt/packages/pull/7112

https://forum.openwrt.org/t/unbound-dns-resolver-process-gradually-consumes-ram-until-none-left-stops-resolving/20660

**Comment by BKPepe** [comment]
Hello @surakin,

Thanks for reporting, but we were aware of this problem as you can see it here: https://github.com/openssl/openssl/issues/7128
Anyway, our developer Honza (@ja-pa) cherry-picked that fix and pushed it into nightly, also we have updated Unbound to version 1.8.0, but as I'm not sure, when we'll release another version of Turris OS, there is a probability, that we'll update it also to 1.8.1, if everything goes well.

I almost forget to tell you that Unbound isn't default DNS resolver on Turris Omnia, where is by default [Knot resolver](https://www.knot-resolver.cz/)
