### ISSUE TITLE
Public static IPv6 prefixes for all Turris devices

### ISSUE THREAD

**Issue by renne** [CZ-NIC/turris-os#88]
The [OpenOverlayRouter](https://openoverlayrouter.org/) package is [on it's way into TurrisOS](https://github.com/CZ-NIC/turris-os-packages/issues/51) (maybe 3.11?).

I suggest to ask @albert-lopez for an IPv6 EID prefix from the [LISP Beta Network](https://www.lisp4.net/beta-network/maintainers/) for testing.

It would be great if CZ.NIC can broker a deal with the [LISP Beta Network](https://www.lisp4.net/beta-network/) to provide each Turris device with a public static IPv6 EID prefix by default. This would allow to run services which need certificates and/or reverse DNS on Turris devices with dynamic IP adresses.

[Discussion](https://forum.turris.cz/t/public-static-ipv6-prefixes-for-all-turris-devices/8618)

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/openwrt/issues/216
