### ISSUE TITLE
[Question] Has Turris OS applied for FSDG Certification?

### ISSUE THREAD

**Issue by asddsaz** [CZ-NIC/turris-os#89]
**Question**: Has Turris applied for [GNU FSDG Certification](https://www.gnu.org/distros/free-system-distribution-guidelines.html)? Considering Turris Routers are fully Open-Source and nothing is hidden in the OS, it should qualify for certification.

**Comment by Cynerd** [comment]
See my forum response: https://forum.turris.cz/t/is-turris-applying-for-ryf-certification/8602/2
